apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-nginx-app
  namespace: argocd
spec:
  description: My Nginx App Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
